### ISSUE TITLE
Correlation Methods not found

### ISSUE THREAD

**Issue by kmezhoud** [radiant-rstats/radiant.basics#1]
Dear Dr. @vnijs ,
In wish panel from Design , Basics, Model, Multivariate,  can I find correlation methods?
https://github.com/radiant-rstats/radiant.basics/blob/master/inst/app/tools/analysis/correlation_ui.R
Thanks,
Karim
```
cor_type <- c("Pearson" = "pearson", "Spearman" = "spearman", "Kendall" = "kendall")

....
  	wellPanel(
	    uiOutput("ui_cor_vars"),
selectInput(inputId = "cor_type", label = "Method:", choices = cor_type, .....

```

**Comment by vnijs** [comment]
In `radiant.basics` ... but you seem to have already found that looking at the link you posted. Not sure what your question is.

https://github.com/radiant-rstats/radiant.basics/blob/master/R/correlation.R

**Comment by kmezhoud** [comment]
OK,
Under ```Basics > Correlation```
Thanks
